export const SONGS = [
  {
    id: 'twinkle',
    title: 'Twinkle Twinkle Little Star',
    level: 1,
    tempo: 80,
    emoji: '⭐',
    notes: [
      { note: 'C4', duration: 'q' },
      { note: 'C4', duration: 'q' },
      { note: 'G4', duration: 'q' },
      { note: 'G4', duration: 'q' },
      { note: 'A4', duration: 'q' },
      { note: 'A4', duration: 'q' },
      { note: 'G4', duration: 'h' },
      { note: 'F4', duration: 'q' },
      { note: 'F4', duration: 'q' },
      { note: 'E4', duration: 'q' },
      { note: 'E4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'C4', duration: 'h' },
      { note: 'G4', duration: 'q' },
      { note: 'G4', duration: 'q' },
      { note: 'F4', duration: 'q' },
      { note: 'F4', duration: 'q' },
      { note: 'E4', duration: 'q' },
      { note: 'E4', duration: 'q' },
      { note: 'D4', duration: 'h' },
      { note: 'C4', duration: 'q' },
      { note: 'C4', duration: 'q' },
      { note: 'G4', duration: 'q' },
      { note: 'G4', duration: 'q' },
      { note: 'A4', duration: 'q' },
      { note: 'A4', duration: 'q' },
      { note: 'G4', duration: 'h' },
      { note: 'F4', duration: 'q' },
      { note: 'F4', duration: 'q' },
      { note: 'E4', duration: 'q' },
      { note: 'E4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'C4', duration: 'h' },
    ],
  },
  {
    id: 'hotcrossbuns',
    title: 'Hot Cross Buns',
    level: 2,
    tempo: 90,
    emoji: '🥐',
    notes: [
      { note: 'E4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'C4', duration: 'h' },
      { note: 'E4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'C4', duration: 'h' },
      { note: 'C4', duration: '8' },
      { note: 'C4', duration: '8' },
      { note: 'C4', duration: '8' },
      { note: 'C4', duration: '8' },
      { note: 'D4', duration: '8' },
      { note: 'D4', duration: '8' },
      { note: 'D4', duration: '8' },
      { note: 'D4', duration: '8' },
      { note: 'E4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'C4', duration: 'h' },
    ],
  },
  {
    id: 'mary',
    title: 'Mary Had a Little Lamb',
    level: 3,
    tempo: 100,
    emoji: '🐑',
    notes: [
      { note: 'E4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'C4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'E4', duration: 'q' },
      { note: 'E4', duration: 'q' },
      { note: 'E4', duration: 'h' },
      { note: 'D4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'D4', duration: 'h' },
      { note: 'E4', duration: 'q' },
      { note: 'G4', duration: 'q' },
      { note: 'G4', duration: 'h' },
      { note: 'E4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'C4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'E4', duration: 'q' },
      { note: 'E4', duration: 'q' },
      { note: 'E4', duration: 'q' },
      { note: 'E4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'E4', duration: 'q' },
      { note: 'D4', duration: 'q' },
      { note: 'C4', duration: 'h' },
    ],
  },
  {
    id: 'happybirthday',
    title: 'Happy Birthday',
    level: 4,
    tempo: 90,
    emoji: '🎂',
    notes: [
      { note: 'C4', duration: '8' },
      { note: 'C4', duration: '8' },
      { note: 'D4', duration: 'q' },
      { note: 'C4', duration: 'q' },
      { note: 'F4', duration: 'q' },
      { note: 'E4', duration: 'h' },
      { note: 'C4', duration: '8' },
      { note: 'C4', duration: '8' },
      { note: 'D4', duration: 'q' },
      { note: 'C4', duration: 'q' },
      { note: 'G4', duration: 'q' },
      { note: 'F4', duration: 'h' },
      { note: 'C4', duration: '8' },
      { note: 'C4', duration: '8' },
      { note: 'C5', duration: 'q' },
      { note: 'A4', duration: 'q' },
      { note: 'F4', duration: 'q' },
      { note: 'E4', duration: 'q' },
      { note: 'D4', duration: 'h' },
      { note: 'A#4', duration: '8' },
      { note: 'A#4', duration: '8' },
      { note: 'A4', duration: 'q' },
      { note: 'F4', duration: 'q' },
      { note: 'G4', duration: 'q' },
      { note: 'F4', duration: 'h' },
    ],
  },
];
